server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Turkey
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: PRODUCT-SERVICE
